version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 smart_home.asgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis

  celery:
    build: ./backend
    command: celery -A smart_home worker -l info --uid=10
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis
      - backend

  celery-beat:
    build: ./backend
    command: celery -A smart_home beat -l info --uid=10
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis
      - backend
      - celery

  rtsp-to-web:
    image: ghcr.io/deepch/rtsptoweb:latest
    volumes:
      - ./rtsp-config:/config
    ports:
      - "8083:8083"
      - "5541:5541"
    restart: unless-stopped

  frontend:
    build: ./frontend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - rtsp-to-web
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html

volumes:
  postgres_data:
