services:
  broker:
    image: nietwid/mqtt-broker
    network_mode: "host"

  router:
    image: nietwid/smart-home-router
    env_file:
      - env/router_prod.env
    network_mode: "host"
    depends_on:
      - broker

