
FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/*.json .
RUN npm install

COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
